CREATE TABLE categories
(
    id INTEGER PRIMARY KEY
);

CREATE TABLE products
(
    id                  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category_id INTEGER REFERENCES categories (id),
    product_name        VARCHAR(255),
    product_create_date DATE,
    sales_count         INTEGER
);

INSERT INTO categories(id)
VALUES (1),
       (2),
       (3);

INSERT INTO products(product_category_id, product_name, product_create_date, sales_count)
VALUES (1, 'A1', '2021-12-04', 1),
       (1, 'B1', '2022-01-05', 0),
       (1, 'C1', '2020-01-01', 1),
       (1, 'D1', '2021-01-02', 1),
       (1, 'E1', '2020-01-01', 0),
       (2, 'A2', '2022-01-17', 10),
       (2, 'B2', '2022-01-15', 25),
       (2, 'C2', '2021-01-01', 5),
       (2, 'D2', '2020-01-01', 50),
       (3, 'A3', '2022-01-20', 0),
       (3, 'B1', '2022-01-17', 0);

WITH ranked_products AS (SELECT p.*,
                                RANK()
                                OVER (PARTITION BY p.product_category_id
                                    ORDER BY p.sales_count DESC, p.product_create_date DESC) AS rnk
                         FROM products p
                         WHERE p.product_create_date > '2020-01-01')
SELECT rp.id,
       rp.product_category_id,
       (SELECT count(*)
        FROM products p
        where p.product_category_id = rp.product_category_id
        GROUP BY p.product_category_id) AS product_count,
       rp.product_name,
       rp.product_create_date,
       rp.sales_count
FROM ranked_products rp
WHERE rnk = 1;