CREATE TABLE categories
(
    id INTEGER PRIMARY KEY
);

CREATE TABLE products
(
    id                INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    productCategoryId INTEGER REFERENCES categories (id),
    productName       VARCHAR(255),
    productCreateDate DATE,
    salesCount        INTEGER
);

INSERT INTO categories(id)
VALUES (1),
       (2),
       (3);

INSERT INTO products(productCategoryId, productName, productCreateDate, salesCount)
VALUES (1, 'A1', '2021-12-04', 1),
       (1, 'B1', '2022-01-05', 0),
       (1, 'C1', '2020-01-01', 1),
       (1, 'D1', '2021-01-02', 1),
       (1, 'E1', '2020-01-01', 0),
       (2, 'A2', '2022-01-17', 10),
       (2, 'B2', '2022-01-15', 25),
       (2, 'C2', '2021-01-01', 5),
       (2, 'D2', '2020-01-01', 50),
       (3, 'A3', '2022-01-20', 0),
       (3, 'B1', '2022-01-17', 0);

WITH RankedProducts AS (SELECT p.*,
                               RANK()
                               OVER (PARTITION BY p.productCategoryId ORDER BY p.salesCount DESC, p.productCreateDate DESC) AS rnk
                        FROM products p
                                 JOIN categories c ON p.productCategoryId = c.id
                        WHERE p.productCreateDate > '2020-01-01')
SELECT id,
       productCategoryId,
       productName,
       productCreateDate,
       salesCount
FROM RankedProducts
WHERE rnk = 1;